# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd2ab537e3bb72f353e01f36a97f12cc92c49aff5cad4ddc526a8b6ebaef386c9f5aef09ec36fe96939ec341cf6ad5f279cfe50a18c6a2e9b3c21855c8518fd7

test:
  secret_key_base: a46762c12ccacf5bc7a4ee7c5752cbbf83a12d86daf1bd5951dcd93ea8b2df4aee14820cd218f7c53c3a31b91651fb0bb40999d47f0436cb1c7fac68af0cbbaa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
